version: "2"

services:
  postgres:
    image: "postgres:12"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  website:
    depends_on:
      - "postgres"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - ".:/fashgram"
    volumes_from:
      - box

  box:
    image: busybox
    volumes:
      - /box

volumes:
  postgres:
  box:
