default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: flashgram_development

test:
  <<: *default
  database: flashgram_test

production:
  <<: *default
  database: flashgram_production
  username: flashgram
  password: <%= ENV['FLASHGRAM_DATABASE_PASSWORD'] %>
